package model;
// Generated 2017-7-1 16:01:00 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Absence generated by hbm2java
 */
public class Absence implements java.io.Serializable {

	private int id;
	private String stuName;
	private Integer groupId;
	private Date date;

	public Absence() {
	}

	public Absence(int id, String stuName) {
		this.id = id;
		this.stuName = stuName;
	}

	public Absence(int id, String stuName, Integer groupId, Date date) {
		this.id = id;
		this.stuName = stuName;
		this.groupId = groupId;
		this.date = date;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getStuName() {
		return this.stuName;
	}

	public void setStuName(String stuName) {
		this.stuName = stuName;
	}

	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
