package model;
// Generated 2017-7-1 16:01:00 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Course generated by hbm2java
 */
public class Course implements java.io.Serializable {

	private int id;
	private String name;
	private Integer teacherId;
	private Date startTime;
	private Date endTime;
	private byte status;

	public Course() {
	}

	public Course(int id, byte status) {
		this.id = id;
		this.status = status;
	}

	public Course(int id, String name, Integer teacherId, Date startTime, Date endTime, byte status) {
		this.id = id;
		this.name = name;
		this.teacherId = teacherId;
		this.startTime = startTime;
		this.endTime = endTime;
		this.status = status;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getTeacherId() {
		return this.teacherId;
	}

	public void setTeacherId(Integer teacherId) {
		this.teacherId = teacherId;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

}
