package model;
// Generated 2017-7-4 15:34:18 by Hibernate Tools 5.2.3.Final

/**
 * GroupMember generated by hbm2java
 */
public class GroupMember implements java.io.Serializable {

	private GroupMemberId id;

	public GroupMember() {
	}

	public GroupMember(GroupMemberId id) {
		this.id = id;
	}

	public GroupMemberId getId() {
		return this.id;
	}

	public void setId(GroupMemberId id) {
		this.id = id;
	}

}
