package model;
// Generated 2017-7-4 15:34:18 by Hibernate Tools 5.2.3.Final

/**
 * Group generated by hbm2java
 */
public class Group implements java.io.Serializable {

	private Integer id;
	private String name;
	private int managerId;
	private byte status;
	private String info;

	public Group() {
	}

	public Group(String name, int managerId, byte status) {
		this.name = name;
		this.managerId = managerId;
		this.status = status;
	}

	public Group(String name, int managerId, byte status, String info) {
		this.name = name;
		this.managerId = managerId;
		this.status = status;
		this.info = info;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getManagerId() {
		return this.managerId;
	}

	public void setManagerId(int managerId) {
		this.managerId = managerId;
	}

	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

}
