package model;
// Generated 2017-7-1 16:01:00 by Hibernate Tools 5.2.3.Final

/**
 * Resources generated by hbm2java
 */
public class Resources implements java.io.Serializable {

	private Integer id;
	private byte[] path;

	public Resources() {
	}

	public Resources(byte[] path) {
		this.path = path;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public byte[] getPath() {
		return this.path;
	}

	public void setPath(byte[] path) {
		this.path = path;
	}

}
