package model;
// Generated 2017-7-3 11:58:05 by Hibernate Tools 5.2.3.Final

/**
 * SubText generated by hbm2java
 */
public class SubText implements java.io.Serializable {

	private int id;
	private int taskId;
	private int textId;
	private int groupId;

	public SubText() {
	}

	public SubText(int id, int taskId, int textId, int groupId) {
		this.id = id;
		this.taskId = taskId;
		this.textId = textId;
		this.groupId = groupId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getTaskId() {
		return this.taskId;
	}

	public void setTaskId(int taskId) {
		this.taskId = taskId;
	}

	public int getTextId() {
		return this.textId;
	}

	public void setTextId(int textId) {
		this.textId = textId;
	}

	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

}
