package model;
// Generated 2017-7-4 15:34:18 by Hibernate Tools 5.2.3.Final

/**
 * TaskManager generated by hbm2java
 */
public class TaskManager implements java.io.Serializable {

	private TaskManagerId id;
	private int groupId;

	public TaskManager() {
	}

	public TaskManager(TaskManagerId id, int groupId) {
		this.id = id;
		this.groupId = groupId;
	}

	public TaskManagerId getId() {
		return this.id;
	}

	public void setId(TaskManagerId id) {
		this.id = id;
	}

	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

}
