package model;
// Generated 2017-7-1 16:01:00 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * Task generated by hbm2java
 */
public class Task implements java.io.Serializable {

	private Integer id;
	private String title;
	private byte[] desc;
	private int courseId;
	private Date startTime;
	private Date endTime;
	private byte status;

	public Task() {
	}

	public Task(String title, int courseId, Date startTime, Date endTime, byte status) {
		this.title = title;
		this.courseId = courseId;
		this.startTime = startTime;
		this.endTime = endTime;
		this.status = status;
	}

	public Task(String title, byte[] desc, int courseId, Date startTime, Date endTime, byte status) {
		this.title = title;
		this.desc = desc;
		this.courseId = courseId;
		this.startTime = startTime;
		this.endTime = endTime;
		this.status = status;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public byte[] getDesc() {
		return this.desc;
	}

	public void setDesc(byte[] desc) {
		this.desc = desc;
	}

	public int getCourseId() {
		return this.courseId;
	}

	public void setCourseId(int courseId) {
		this.courseId = courseId;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

}
