package model;
// Generated 2017-7-3 11:58:05 by Hibernate Tools 5.2.3.Final

/**
 * Text generated by hbm2java
 */
public class Text implements java.io.Serializable {

	private Integer id;
	private byte[] content;

	public Text() {
	}

	public Text(byte[] content) {
		this.content = content;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public byte[] getContent() {
		return this.content;
	}

	public void setContent(byte[] content) {
		this.content = content;
	}

}
